### ISSUE TITLE
Сырость для релиза

### ISSUE THREAD

**Issue by lgXenos** [floor12/yii2-module-banner#3]
1. В ридми, описывая миграции путь заканчивается на не src, а src/migrations
2. При пустой базе кнопка "Добавить банер" отваливается с JS ошибкой, что нет showForm, т.к. этот ассет подключается только при кнопках правки, и не подключается при создании
3. В момент рендера формы добавления, когда уже поправил все что падало, код все равно падает на поле desktop_image с подписью, что у ActiveRecord нет доступа к БД..

После этого я сдался и удалил данный реп
Если автор еще поддерживает это - буду рад вернуться к тестам после правки ошибок **для пустого проекта**

**Comment by floor12** [comment]
Автор поддерживает мало по мало. 
Спасибо за фидбек. Доку поправлю, скорректирую ассеты для скриптов. А по поводу пункта номер 3 - хотелось бы побольше информации.  Но в любом случаю, попробую на чистом basic проекте.  У просто свой форк basic с уже поставленными и рабочими всеми моими необходимыми для жизни модулями...
В любом случае спасибо, отпишу сдесь о результатах.

**Comment by lgXenos** [comment]
Спасибо за быстрый ответ
Проблема третьего пункта в том, что 
1. У меня не открылось попапа. У меня просто произошел переход. Может чего-то не хватает в зависимостях. Не знаю
2. В файле form.php там идет рендер файловых полей виджетом. И именно отсюда идет непонятный back-trace, который заканчивается ошибкой самого Yii, что DB Builder не получил коннект к базе
https://github.com/floor12/yii2-module-banner/blob/master/src/views/admin/_form_banner.php#L76

Я не смог понять связи между этим... 
Описываю исключительно что произошло

PS: шаблон у меня advanced, но полагаю, что это не важно
:)

**Comment by floor12** [comment]
Ну твой issue побудил меня заняться модулем и причесать его немного для адекватного использования другими людьми. Поэтому сижу привожу его в порядок сейчас - так что, надеюсь, скоро будет обновленная версия, работающая "из коробки".

**Comment by floor12** [comment]
Только что опубликовал сильно доработанную версию версию 1.2.13, включающее обновление документации.  Прошу проверить работу, выполнив шаги из новой документации.

В старой документации не было вообще ничего сказано про необходимость подключить зависимый модуль и выполнить его миграции.

**Comment by lgXenos** [comment]
Банер не отобразился
![image](https://user-images.githubusercontent.com/14957311/79340649-47a0c680-7f33-11ea-9c0a-d078f37ca8ba.png)

```
yii\web\NotFoundHttpException: Запрашиваемый файл не найден на диске. 
in \vendor\floor12\yii2-module-files\src\controllers\DefaultController.php:237
Stack trace:
#0 [internal function]: floor12\files\controllers\DefaultController->actionImage('927dc54129f0d11...', '100', '60', '1')
#1 \vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#2 \vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#3 \vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('image', Array)
```
Ну и так, по мелочи
![image](https://user-images.githubusercontent.com/14957311/79340024-6c486e80-7f32-11ea-86a5-13cd87680361.png)

**Comment by lgXenos** [comment]
На счет того, что в базе
![image](https://user-images.githubusercontent.com/14957311/79343167-bf242500-7f36-11ea-9c91-cbbf1232e4ee.png)

**Comment by lgXenos** [comment]
Теперь немного идеологии

Статистика неверная. Она считает +1 в просмотр даже если я просто исходный код страницы открою. А должна - когда файловый компонент отдал рисунок

Передавая параметры размера в урле - ты провоцируешь, что тебе положат сервер, передавая разные размеры и заставляя твой бекенд их рендерить каждый раз

**Comment by floor12** [comment]
Привет. Смотри какие мысли. Для начала уточню, что все проблемы обсуждаемые сейчас касаются другого модуля, yii2-module-files, который управляет работой файлов в этом модуле, то есть речь далее пойдет о нем.

Что касается передачи параметров размера картинки в урле, то теоретически ты прав, и этот вариант развития возможен.  Решаться он будет в ближайшее опциональной передачей в поведение тех размеров, которые разрешено запрашивать. Однако, хочу заметить, что я встречал такую систему на достаточно крупных сайтах (например audi), и на нескольких десятков моих сайтов с суммарной посещаемостью в десятки тысяч в сутки, эта проблема тоже ни разу не случалась. Если бы она случалась, вероятно, я дописал бы этот функционал в 10 строчек несколько раньше ) Но пока это в планах (Кстати никто не мешает сделать пул-реквест).

Что касается отсчета просмотров, то тоже позволь с тобой полностью согласиться, подсчет достаточно примитивный. Для того, чтобы он работал так, как предлагаешь ты, нужно переложить функционал отдачи картинки с модуля файлов на модуль баннеров. Сделать это можно, создав соответсвующий action с использованием хелперов из модуля файлов. Возможно стоит этим заняться, но, опять же, ты первый кто обратил на это внимание.

Ну и последнее это непосредственно твоя проблема с файлом. Мне тут тебе сложно помочь, могу только предположить что проблема может быть из-за advanced приложения или прав. Посмотри документацию по модулю файлов, проверь как где у тебя планируется папка для файлов и кеша превьюшек, если права на ее запись-создание. Возможно фронтенд и бекенд приложения ищут эту папку относительно себя. Я вижу что у тебя винда, поэтому в принципе могут быть теоретические проблемы с обратными слешами. 

А опечатки надо не поправить, в просто добавить нормальный i18n в этот модуль.

**Comment by lgXenos** [comment]
Хорошо, спасибо
Проект уже запускается - и хорошо)
