### ISSUE TITLE
SlickAssert and Bootstrap4

### ISSUE THREAD

**Issue by klunker** [floor12/yii2-module-banner#4]
Привет, есть такая интересная проблема.
Виджет отображения баннера для сайта использует bootstrap3
`  
    public $depends = [
        'yii\web\JqueryAsset',
        'yii\bootstrap\BootstrapAsset',
    ];`

в проекте используется bootstrap4 в результате ломается вся верстка. 

Если `'yii\bootstrap\BootstrapAsset',` замменить на `'yii\bootstrap4\BootstrapAsset',`, то все становиться ок. Но изменять Ваши файлы как-то не ок , в случае обновления могут быть проблемы. Как подскажите поступить?

**Comment by floor12** [comment]
Надо добавить в параметры настройки модуля какую именно зависимость использовать. Я могу это сделать в течение нескольких дней, или можешь сделать сам и сделать пул-реквест. 
То есть надо в `floor12\banner\Module` добавить новое поле типа $bootstrapAsset = 'yii\bootstrap\BootstrapAsset';
Во всех файлах модуля брать эту зависимость через Yii::getModule('banner')->bootstrapAsset, а в конфиге приложения уже прописать 4й бутстрап для этого параметра.
